
var __cov_dsg3PfnNxcOYeh8JHTqE_w = (Function('return this'))();
if (!__cov_dsg3PfnNxcOYeh8JHTqE_w.__coverage__) { __cov_dsg3PfnNxcOYeh8JHTqE_w.__coverage__ = {}; }
__cov_dsg3PfnNxcOYeh8JHTqE_w = __cov_dsg3PfnNxcOYeh8JHTqE_w.__coverage__;
if (!(__cov_dsg3PfnNxcOYeh8JHTqE_w['C:\\Users\\priyankam\\Desktop\\todo-angular-master\\e2e\\protractor.conf.js'])) {
   __cov_dsg3PfnNxcOYeh8JHTqE_w['C:\\Users\\priyankam\\Desktop\\todo-angular-master\\e2e\\protractor.conf.js'] = {"path":"C:\\Users\\priyankam\\Desktop\\todo-angular-master\\e2e\\protractor.conf.js","s":{"1":0,"2":0,"3":0,"4":0},"b":{},"f":{"1":0,"2":0},"fnMap":{"1":{"name":"(anonymous_1)","line":21,"loc":{"start":{"line":21,"column":11},"end":{"line":21,"column":22}}},"2":{"name":"(anonymous_2)","line":23,"loc":{"start":{"line":23,"column":11},"end":{"line":23,"column":14}}}},"statementMap":{"1":{"start":{"line":4,"column":0},"end":{"line":4,"column":58}},"2":{"start":{"line":6,"column":0},"end":{"line":29,"column":2}},"3":{"start":{"line":24,"column":4},"end":{"line":26,"column":7}},"4":{"start":{"line":27,"column":4},"end":{"line":27,"column":90}}},"branchMap":{}};
}
__cov_dsg3PfnNxcOYeh8JHTqE_w = __cov_dsg3PfnNxcOYeh8JHTqE_w['C:\\Users\\priyankam\\Desktop\\todo-angular-master\\e2e\\protractor.conf.js'];
__cov_dsg3PfnNxcOYeh8JHTqE_w.s['1']++;const {SpecReporter}=require('jasmine-spec-reporter');__cov_dsg3PfnNxcOYeh8JHTqE_w.s['2']++;exports.config={allScriptsTimeout:11000,specs:['./src/**/*.e2e-spec.ts'],capabilities:{'browserName':'chrome'},directConnect:true,baseUrl:'http://localhost:4200/',seleniumAddress:'http://localhost:4444/wd/hub',framework:'jasmine',jasmineNodeOpts:{showColors:true,defaultTimeoutInterval:30000,print:function(){__cov_dsg3PfnNxcOYeh8JHTqE_w.f['1']++;}},onPrepare(){__cov_dsg3PfnNxcOYeh8JHTqE_w.f['2']++;__cov_dsg3PfnNxcOYeh8JHTqE_w.s['3']++;require('ts-node').register({project:require('path').join(__dirname,'./tsconfig.e2e.json')});__cov_dsg3PfnNxcOYeh8JHTqE_w.s['4']++;jasmine.getEnv().addReporter(new SpecReporter({spec:{displayStacktrace:true}}));}};
