
var __cov_QeoIt2VSJ5PrI1IRxZD9vg = (Function('return this'))();
if (!__cov_QeoIt2VSJ5PrI1IRxZD9vg.__coverage__) { __cov_QeoIt2VSJ5PrI1IRxZD9vg.__coverage__ = {}; }
__cov_QeoIt2VSJ5PrI1IRxZD9vg = __cov_QeoIt2VSJ5PrI1IRxZD9vg.__coverage__;
if (!(__cov_QeoIt2VSJ5PrI1IRxZD9vg['C:\\Users\\priyankam\\Desktop\\todo-angular-master\\Reusablemethods.js'])) {
   __cov_QeoIt2VSJ5PrI1IRxZD9vg['C:\\Users\\priyankam\\Desktop\\todo-angular-master\\Reusablemethods.js'] = {"path":"C:\\Users\\priyankam\\Desktop\\todo-angular-master\\Reusablemethods.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0},"b":{},"f":{"1":0,"2":0,"3":0,"4":0,"5":0},"fnMap":{"1":{"name":"(anonymous_1)","line":1,"loc":{"start":{"line":1,"column":26},"end":{"line":1,"column":37}}},"2":{"name":"(anonymous_2)","line":3,"loc":{"start":{"line":3,"column":20},"end":{"line":3,"column":41}}},"3":{"name":"(anonymous_3)","line":7,"loc":{"start":{"line":7,"column":21},"end":{"line":7,"column":37}}},"4":{"name":"(anonymous_4)","line":11,"loc":{"start":{"line":11,"column":20},"end":{"line":11,"column":34}}},"5":{"name":"(anonymous_5)","line":15,"loc":{"start":{"line":15,"column":23},"end":{"line":15,"column":37}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":19,"column":6}},"2":{"start":{"line":3,"column":4},"end":{"line":14,"column":5}},"3":{"start":{"line":4,"column":8},"end":{"line":4,"column":41}},"4":{"start":{"line":5,"column":8},"end":{"line":5,"column":29}},"5":{"start":{"line":8,"column":8},"end":{"line":8,"column":46}},"6":{"start":{"line":9,"column":8},"end":{"line":9,"column":27}},"7":{"start":{"line":12,"column":8},"end":{"line":12,"column":46}},"8":{"start":{"line":13,"column":8},"end":{"line":13,"column":27}},"9":{"start":{"line":15,"column":4},"end":{"line":18,"column":5}},"10":{"start":{"line":16,"column":8},"end":{"line":16,"column":51}},"11":{"start":{"line":17,"column":8},"end":{"line":17,"column":27}},"12":{"start":{"line":20,"column":4},"end":{"line":20,"column":47}}},"branchMap":{}};
}
__cov_QeoIt2VSJ5PrI1IRxZD9vg = __cov_QeoIt2VSJ5PrI1IRxZD9vg['C:\\Users\\priyankam\\Desktop\\todo-angular-master\\Reusablemethods.js'];
__cov_QeoIt2VSJ5PrI1IRxZD9vg.s['1']++;var Reusablemethodspage=function(){__cov_QeoIt2VSJ5PrI1IRxZD9vg.f['1']++;__cov_QeoIt2VSJ5PrI1IRxZD9vg.s['2']++;this.enterData=function(iddata,data){__cov_QeoIt2VSJ5PrI1IRxZD9vg.f['2']++;__cov_QeoIt2VSJ5PrI1IRxZD9vg.s['3']++;var email=element(by.id(iddata));__cov_QeoIt2VSJ5PrI1IRxZD9vg.s['4']++;email.sendKeys(data);},this.buttonclick=function(iddata){__cov_QeoIt2VSJ5PrI1IRxZD9vg.f['3']++;__cov_QeoIt2VSJ5PrI1IRxZD9vg.s['5']++;var submitlink=element(by.id(iddata));__cov_QeoIt2VSJ5PrI1IRxZD9vg.s['6']++;submitlink.click();},this.searchData=function(data){__cov_QeoIt2VSJ5PrI1IRxZD9vg.f['4']++;__cov_QeoIt2VSJ5PrI1IRxZD9vg.s['7']++;var searchtodo=element(by.name(data));__cov_QeoIt2VSJ5PrI1IRxZD9vg.s['8']++;searchtodo.click();};__cov_QeoIt2VSJ5PrI1IRxZD9vg.s['9']++;this.searchdelData=function(data){__cov_QeoIt2VSJ5PrI1IRxZD9vg.f['5']++;__cov_QeoIt2VSJ5PrI1IRxZD9vg.s['10']++;var searchtodo=element(by.className(data));__cov_QeoIt2VSJ5PrI1IRxZD9vg.s['11']++;searchtodo.click();};};__cov_QeoIt2VSJ5PrI1IRxZD9vg.s['12']++;module.exports=new Reusablemethodspage();
